export { GIS_MODULE_ID, gisModule, type GisModuleOptions } from './module'
export { gisMessages } from './i18n'
export { MapView, type MapViewProps, type WmsLayerSpec } from './components/LazyMapView'
export { GeometryField } from './components/GeometryField'
export { useFeatures } from './api'
export { featureIdOf, geometryFields } from './lib/geo'
export { WMS_TILE_SIZE, wmsTileUrl } from './lib/wms'
export type { Feature, FeatureCollection, GeoJsonGeometry, GeometryMeta, GeometryType } from './types'
